- name: 'Taking metrics from my PC'
  hosts: localhost  
  tasks:
  - name: 'Install iostat'
    apt:
      name: sysstat
  
  - name: 'Create File to direct iostat output'
    file: 
      path: ./salida_iostat.json
      state: touch
      mode: u=rw,g=rw,o=rw
  
  - name: 'Run iostat and get output into json'
    raw: iostat -c -o JSON > ./salida_iostat.json
  
  - name: 'Create Temp File to direct free output'
    file: 
      path: ./salida_free.txt
      state: touch
      mode: u=rw,g=rw,o=rw
  
  - name: 'Run free and get output into txt'
    raw: free --mega > ./salida_free.txt
  
  - name: 'Parse Raw Free text into JSON'
    raw: bash parse_free.sh | jq > ./salida_free.json

  - name: 'Remove Temp File that saved free output'
    file: 
      path: ./salida_free.txt
      state: absent

  - name: 'Create database'
    influxdb_database:
        hostname: "localhost"
        port: 8086
        udp_port: 4444
        username: "admin"
        password: "admin"
        database_name: "Carga_ansible"

  - name: 'Save the iostat JSON file data to a Variable as a Fact'
    set_fact:
      iostat_jsondata: "{{ lookup('file','salida_iostat.json') | from_json }}"

  - name: 'Save the free JSON file data to a Variable as a Fact'
    set_fact:
      free_jsondata: "{{ lookup('file','salida_free.json') | from_json }}"     

  - name: 'Query the iostat JSON file content to get relevant values'
    set_fact:
      node_name: "{{iostat_jsondata | json_query(jmesquery_node)}}"
      sys_name: "{{iostat_jsondata | json_query(jmesquery_system)}}"
      cpu_user: "{{ iostat_jsondata | json_query(jmesquery1) }}"
      cpu_nice: "{{ iostat_jsondata | json_query(jmesquery2) }}"
      cpu_system: "{{ iostat_jsondata | json_query(jmesquery3) }}"
      cpu_iowait: "{{ iostat_jsondata | json_query(jmesquery4) }}"
      cpu_steal: "{{ iostat_jsondata | json_query(jmesquery5) }}"
      cpu_idle: "{{ iostat_jsondata | json_query(jmesquery6) }}"
      
    vars:
      jmesquery_node: 'sysstat.hosts[0].nodename'
      jmesquery_system: 'sysstat.hosts[0].sysname'
      jmesquery1: 'sysstat.hosts[0].statistics[0]."avg-cpu".user'
      jmesquery2: 'sysstat.hosts[0].statistics[0]."avg-cpu".nice'
      jmesquery3: 'sysstat.hosts[0].statistics[0]."avg-cpu".system'
      jmesquery4: 'sysstat.hosts[0].statistics[0]."avg-cpu".iowait'
      jmesquery5: 'sysstat.hosts[0].statistics[0]."avg-cpu".steal'
      jmesquery6: 'sysstat.hosts[0].statistics[0]."avg-cpu".idle'
  
  - name: 'Query the iostat JSON file content to get relevant values'
    set_fact:
      mem_total: "{{ free_jsondata | json_query(jmesquery1) }}"
      mem_en_uso: "{{ free_jsondata | json_query(jmesquery2) }}"
      mem_libre: "{{ free_jsondata | json_query(jmesquery3) }}"
      mem_compartida: "{{ free_jsondata | json_query(jmesquery4) }}"
      mem_buffcache: "{{ free_jsondata | json_query(jmesquery5) }}"
      mem_disponible: "{{ free_jsondata | json_query(jmesquery6) }}"
    
    vars:
      jmesquery1: 'Memoria_Total'
      jmesquery2: 'Memoria_EnUso'
      jmesquery3: 'Memoria_Libre'
      jmesquery4: 'Memoria_Compartida'
      jmesquery5: 'Memoria_BuffCache'
      jmesquery6: 'Memoria_Disponible'

  - name: 'Imprimir variables para test'
    debug:
      msg: 
        - "User: {{cpu_user}} System: {{mem_total}}"
        - "CPU_USER: {{cpu_user}}"
        - "CPU_IDLE: {{cpu_idle}}"
        - "CPU_IDLE: {{cpu_system}}"
        - "MEMORY_TOTAL: {{mem_total}}"

  
  - name: Write points into database
    influxdb_write:
        hostname: "localhost"
        database_name: "Carga_ansible"
        udp_port: 4444
        data_points:
          - measurement: pc_stats
            tags:
              node_name: "{{ node_name }}"
              system_name: "{{ sys_name }}"
            time: "{{ ansible_date_time.iso8601 }}"
            fields:
              cpu_user: "{{ cpu_user }}"
              cpu_nice: "{{ cpu_nice | float }}"
              cpu_system: "{{ cpu_system | float }}"
              cpu_iowait: "{{ cpu_iowait |float }}"
              cpu_steal: "{{ cpu_steal | float}}"
              cpu_idle: "{{ cpu_idle | float }}"
              mem_total: "{{ mem_total }}" 
              mem_en_uso: "{{ mem_en_uso }}"
              mem_libre: "{{ mem_libre }}"
              mem_compartida: "{{ mem_compartida }}"
              mem_buffcache: "{{ mem_buffcache }}"
              mem_disponible: "{{ mem_disponible }}"